// Package application projects servers into the formats external systems consume.
//
// Prometheus, the embedded runner, and external diagnostics all consume the same
// server projection. Keeping inventory generation in one use case preserves stable
// identity and avoids a second targeting database.
//
// See docs/decisions/003-metrics-label-contract.md and
// docs/decisions/006-embedded-ansible-execution.md.
package application

import (
	"context"
	"fmt"
	"sort"
	"strings"

	serverdomain "github.com/maple52046/swallow/internal/server/domain"
)

// defaultProvisioningState restricts discovery to machines that are actually running
// an operating system.
//
// A machine in "ready" state is powered off by definition, so including it would add a
// permanently failing scrape target and an unreachable automation host. Callers that
// want everything can ask for it explicitly.
const defaultProvisioningState = "deployed"

// PrometheusTarget is one entry in a Prometheus http_sd response.
type PrometheusTarget struct {
	Targets []string          `json:"targets"`
	Labels  map[string]string `json:"labels"`
}

// AnsibleInventory is the JSON an Ansible dynamic inventory source returns.
//
// Groups are a flat map alongside the reserved "_meta" and "all" keys, which is the
// shape Ansible expects rather than something chosen here.
type AnsibleInventory map[string]any

// AnsibleGroup is one group's membership.
type AnsibleGroup struct {
	// bson omitempty matters as much as json: this inventory is frozen into Mongo for a
	// durable Ansible Task, and without it a nil Children/Hosts slice is stored as BSON
	// null. Ansible's script inventory plugin then fails with "'NoneType' object is not
	// iterable", leaving a deploy with no hosts to target.
	Hosts    []string `json:"hosts,omitempty" bson:"hosts,omitempty"`
	Children []string `json:"children,omitempty" bson:"children,omitempty"`
}

type DiscoveryInput struct {
	SiteID string
	// ProvisioningState defaults to "deployed". The literal "all" removes the filter.
	ProvisioningState string
	// Port is the exporter port for Prometheus targets. One swallow endpoint serves
	// several scrape jobs — node_exporter on 9100, the RDC exporter on 5000 — by being
	// asked for a different port each time.
	Port int
	// Tag restricts targets to servers carrying this provisioner tag. It is how the
	// RDC exporter scrape job asks for AMD GPU servers only (tag "amd-gpu"): the caller
	// names the tag, so the endpoint does not encode what a server type means.
	Tag string
}

type DiscoveryUseCase struct {
	servers serverdomain.ServerRepository
}

func NewDiscoveryUseCase(servers serverdomain.ServerRepository) *DiscoveryUseCase {
	return &DiscoveryUseCase{servers: servers}
}

// PrometheusTargets returns scrape targets carrying the label contract.
//
// Labels are attached here, which is the whole point: the join key between a metric and
// a server is generated by the same component that owns server identity, so it cannot
// drift from it.
func (uc *DiscoveryUseCase) PrometheusTargets(ctx context.Context, input DiscoveryInput) ([]PrometheusTarget, error) {
	servers, err := uc.discoverable(ctx, input)
	if err != nil {
		return nil, err
	}

	targets := make([]PrometheusTarget, 0, len(servers))
	for _, server := range servers {
		address := server.PrimaryAddress()
		if address == "" {
			// Nothing to scrape. Emitting a target with no address would create a
			// permanently failing series attributed to this server.
			continue
		}

		labels := map[string]string{
			"server_id": server.ID,
			"site":      server.Source.SiteID,
		}
		if m := server.Membership; m != nil && m.PlatformID != "" {
			labels["platform_id"] = m.PlatformID
			labels["cluster"] = m.PlatformID
		}

		targets = append(targets, PrometheusTarget{
			Targets: []string{fmt.Sprintf("%s:%d", address, input.Port)},
			Labels:  labels,
		})
	}
	return targets, nil
}

// AnsibleInventory returns the canonical dynamic inventory shape.
//
// Hosts are keyed by server ID with ansible_host carrying the address, so that a
// playbook and its output refer to swallow's stable identifier rather than to an IP that
// changes on every reinstall.
func (uc *DiscoveryUseCase) AnsibleInventory(ctx context.Context, input DiscoveryInput) (AnsibleInventory, error) {
	servers, err := uc.discoverable(ctx, input)
	if err != nil {
		return nil, err
	}

	hostvars := map[string]any{}
	groups := map[string][]string{}

	for _, server := range servers {
		address := server.PrimaryAddress()
		if address == "" {
			// Unreachable, so including it would only produce a task failure.
			continue
		}

		vars := map[string]any{
			"ansible_host":        address,
			"server_id":           server.ID,
			"site_id":             server.Source.SiteID,
			"integration_id":      server.Source.IntegrationID,
			"provider_machine_id": server.Source.ProviderMachineID,
			"hostname":            server.Observed.Hostname,
			"fqdn":                server.Observed.FQDN,
			"architecture":        server.Observed.Architecture,
			"cpu_cores":           server.Observed.CPUCores,
			"memory_mib":          server.Observed.MemoryMiB,
		}

		addGroup(groups, "site_"+groupToken(server.Source.SiteID), server.ID)

		// The effective Server Default User (decision 045): the value set on the Server, else the
		// image's. The runner turns it into ansible_user, so it is emitted only when known and its
		// absence means "fall back to probing".
		if defaultUser, _ := server.EffectiveDefaultUser(); defaultUser != "" {
			vars["default_user"] = defaultUser
		}

		if p := server.Provisioning; p != nil {
			vars["provisioning_state"] = p.State
			vars["os_system"] = p.OSSystem
			vars["distro_series"] = p.DistroSeries
			// The deployed image's default login user (decision 039), kept for playbooks that want
			// the image's value; emitted only when known.
			if p.DeployedImageDefaultUser != "" {
				vars["image_default_user"] = p.DeployedImageDefaultUser
			}
			addGroup(groups, "provisioning_"+groupToken(p.State), server.ID)
		}

		if m := server.Membership; m != nil {
			vars["platform_id"] = m.PlatformID
			vars["platform_role"] = m.Role
			vars["platform_node_name"] = m.NodeName
			if m.PlatformID != "" {
				addGroup(groups, "platform_"+groupToken(m.PlatformID), server.ID)
			}
			if m.Role != "" {
				addGroup(groups, "role_"+groupToken(m.Role), server.ID)
			}
		}

		if vendors := gpuVendors(server); len(vendors) > 0 {
			vars["gpu_vendors"] = vendors
			for _, vendor := range vendors {
				addGroup(groups, "gpu_"+groupToken(vendor), server.ID)
			}
		}

		// Provisioner tags become both a host var and one group per tag, so a playbook
		// can target a server type by group — e.g. the RDC exporter play runs on
		// "tag_amd_gpu". The host var is named server_tags, not tags, because "tags" is a
		// reserved Ansible variable. The group name is tokenized the same way as the others.
		if len(server.Observed.Tags) > 0 {
			vars["server_tags"] = server.Observed.Tags
			for _, tag := range server.Observed.Tags {
				if tag == "" {
					continue
				}
				addGroup(groups, "tag_"+groupToken(tag), server.ID)
			}
		}

		hostvars[server.ID] = vars
	}

	inventory := AnsibleInventory{
		"_meta": map[string]any{"hostvars": hostvars},
	}

	children := make([]string, 0, len(groups))
	for name, hosts := range groups {
		inventory[name] = AnsibleGroup{Hosts: hosts}
		children = append(children, name)
	}
	// Sorted for a stable response, and written as a map so that "children" is always
	// present as an array. An inventory with no hosts is a normal early state, and
	// omitting the key there makes some parsers treat the document as malformed.
	sort.Strings(children)
	inventory["all"] = map[string]any{"children": children}

	return inventory, nil
}

func (uc *DiscoveryUseCase) discoverable(ctx context.Context, input DiscoveryInput) ([]*serverdomain.Server, error) {
	state := input.ProvisioningState
	if state == "" {
		state = defaultProvisioningState
	}
	if state == "all" {
		state = ""
	}

	// Limit 0 means unlimited: a scrape target list or an automation inventory has to
	// be complete, so this is the one read that must never be paginated.
	result, err := uc.servers.List(ctx, serverdomain.ListFilter{
		SiteID:            input.SiteID,
		ProvisioningState: state,
		Tag:               input.Tag,
		Limit:             0,
	})
	if err != nil {
		return nil, err
	}
	return result.Servers, nil
}

func gpuVendors(server *serverdomain.Server) []string {
	seen := map[string]bool{}
	var vendors []string
	for _, gpu := range server.Observed.GPUs {
		vendor := strings.ToLower(gpu.Vendor)
		if vendor == "" || seen[vendor] {
			continue
		}
		seen[vendor] = true
		vendors = append(vendors, vendor)
	}
	return vendors
}

func addGroup(groups map[string][]string, name, serverID string) {
	groups[name] = append(groups[name], serverID)
}

// groupToken makes a value safe as an Ansible group name, which may only contain
// letters, digits, and underscores.
func groupToken(value string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(value) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '_':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}
